### ISSUE TITLE
Issue with testing - ds-token/delegate.sol not found

### ISSUE THREAD

**Issue by cryptohariseldon** [reflexer-labs/geb#113]
Hi,

In attempting to run the build command for testing the contracts -
`dapp --use solc:0.6.7 build`

Following file not found errors show up, all referencing ds-token/delegate.sol ->

`rc/test/shared/Coin.t.sol:21:1: ParserError: Source "ds-token/delegate.sol" not found: File not found.
import "ds-token/delegate.sol";
^-----------------------------^
src/test/single/SingleCollateralAuctionHouse.t.sol:4:1: ParserError: Source "ds-token/delegate.sol" not found: File not found.
import {DSDelegateToken} from "ds-token/delegate.sol";
^----------------------------------------------------^
src/test/single/SingleDebtAuctionHouse.t.sol:4:1: ParserError: Source "ds-token/delegate.sol" not found: File not found.
import {DSDelegateToken} from "ds-token/delegate.sol";
^----------------------------------------------------^
src/test/single/SingleGlobalSettlement.t.sol:23:1: ParserError: Source "ds-token/delegate.sol" not found: File not found.
import "ds-token/delegate.sol";
^-----------------------------^
src/test/single/SingleSAFEEngine.t.sol:5:1: ParserError: Source "ds-token/delegate.sol" not found: File not found.
import "ds-token/delegate.sol";
^-----------------------------^
src/test/single/SingleSaveSAFE.t.sol:5:1: ParserError: Source "ds-token/delegate.sol" not found: File not found.
import "ds-token/delegate.sol";
^-----------------------------^
src/test/single/SingleSettlementSurplusAuctioneer.t.sol:4:1: ParserError: Source "ds-token/delegate.sol" not found: File not found.
import {DSDelegateToken} from "ds-token/delegate.sol";
^----------------------------------------------------^
src/test/single/SingleStakingPoolIntegration.t.sol:4:1: ParserError: Source "ds-token/delegate.sol" not found: File not found.
import {DSDelegateToken} from "ds-token/delegate.sol";
^----------------------------------------------------^
src/test/single/SingleSurplusAuctionHouse.t.sol:4:1: ParserError: Source "ds-token/delegate.sol" not found: File not found.
import {DSDelegateToken} from "ds-token/delegate.sol";
^----------------------------------------------------^
`

The dapphub [repo for ds-token](https://github.com/dapphub/ds-token/blob/master/src/token.sol) also does not contain the delegate.sol contract. Maybe there was an update or you have this file available in one of the other repos? Thanks.

**Comment by fabiohild** [comment]
Hello @cryptohariseldon , I think all you need to do is call ```dapp update```.  It will clone all dependencies and then running the tests should go fine. 

Regarding ds-token (and other repos), always use the ones on our organization as they are different from the dss ones.

Let me know if this works. Cheers
