### ISSUE TITLE
Misleading comment?

### ISSUE THREAD

**Issue by bkellerman** [reflexer-labs/geb#68]
https://github.com/reflexer-labs/geb/blob/6fcbc5b8dd4f5528f43bc56929d709dcb1bc7ddf/src/CollateralAuctionHouse.sol#L75

It looks like one final settling bid can be placed after the deadline.

Maybe, "deadline after which the auction can be settled" ?

**Comment by bkellerman** [comment]
@stefanionescu

**Comment by stefanionescu** [comment]
You mean in the case of FixedDiscount?

**Comment by bkellerman** [comment]
Yes

**Comment by stefanionescu** [comment]
Fixed

https://github.com/reflexer-labs/geb/blob/cbe4c6f50e8fc25fcd380206b31c580e23a979d9/src/CollateralAuctionHouse.sol#L405
